version: '3.3'

services:
#  db:
#    container_name: db
#    image: postgres:latest
#    restart: always
#    environment:
#      - POSTGRES_DB=backend
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=qwerty
#    expose:
#      - '5432:5432'
#    volumes:
#      - .:/var/lib/postgresql/data/\

    db:
      image: postgres
      volumes:
        - ./data/db:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=backend
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=qwerty

  backend:
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    volumes:
      - .:/code
    command:
      - python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
